[package]
name = "carpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
serde = "1.0.143"
serde_derive = "1.0.143"
toml = "0.5.9"
